"""empty message

Revision ID: 9e33d2999014
Revises: 
Create Date: 2020-05-02 16:05:00.489058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e33d2999014'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_date')
    op.drop_column('actors', 'gender')
    # ### end Alembic commands ###
